---
abstract: 'Return zodiac for a given date'
author:
  - 'Maroš Kollár'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Event-Zodiac
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DateTime: 0
  DateTime::Astro: 0
  Exporter: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.03
